[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "pdaf-observation-file-generator"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "pandas",
    "netCDF4",
    "gitpython",
]

[tool.setuptools]
packages = []
